# Generated by Django 3.1 on 2022-07-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20220708_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='s',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
