# Generated by Django 3.1 on 2022-07-08 10:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactus', '0003_auto_20220708_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Us',
            new_name='ContactUs',
        ),
    ]
