# Generated by Django 3.1 on 2022-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Paytm', 'Paytm'), ('COD', 'COD')], default='COD', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Paytm', 'Paytms'), ('COD', 'COD')], default='COD', max_length=100),
        ),
    ]
