# Generated by Django 3.1 on 2022-07-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20220704_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='signature_id',
        ),
    ]
